### ISSUE TITLE
Mod does not support multiplayer servers

### ISSUE THREAD

**Issue by felinusfish** [MacaylaMarvelous81/DatapackInstaller#1]
The mod doesn't support multiplayer servers, which is a great use case as being able to add the datapacks to the world without having to go through the trouble of creating a singleplayer world and moving it to the server is useful.

**Comment by MacaylaMarvelous81** [comment]
I'd love to support this, but could you clarify what how you're moving the server to the world? As far as I know, you can't import worlds into Minecraft servers from within Minecraft. Do you mean getting the server software to add datapacks its world(s) 
from some common directory automatically or are you importing a world into a Realm?

**Comment by felinusfish** [comment]
Typically you'd have to create the world in singleplayer, then move it from your worlds folder into the server's root folder. Obviously a hassle if you're constantly resetting the world (and sure, I guess I could leave the datapack folder in the world folder when I delete it but.. very inconvenient)

**Comment by MacaylaMarvelous81** [comment]
Would it work for you if datapacks automatically get copied to the active or new world?

**Comment by ekul6547** [comment]
This feature would be nice as I'm setting up a modded server.
Every time I add a new biome mod or something adding new world generation like that, I'm deleting and regenerating the entire world.
So it would be nice not to have to manually move over the datapacks each time.

**Comment by MacaylaMarvelous81** [comment]
85d7490 Here's a basic implementation for dedicated servers. It'll copy data packs from 'datapacks' to the active world.
