### ISSUE TITLE
Change "installed_datapacks" folder to simply "datapacks"

### ISSUE THREAD

**Issue by super4z** [MacaylaMarvelous81/DatapackInstaller#2]
Change *installed_datapacks* folder to simply *datapacks* to better support the Modrinth app's implementation of installing datapacks

**Comment by MacaylaMarvelous81** [comment]
Sure, I can do that. I think I'll use both 'installed_datapacks' and 'datapacks' so upgrades from previous versions can work without additional configuration.

**Comment by MacaylaMarvelous81** [comment]
done in new release

**Comment by MacaylaMarvelous81** [comment]
c81a0ab: Now 'datapacks' will work only because of f1014d2. 'installed_datapacks' will try to be renamed to 'datapacks', but if you have both 'datapacks' and 'installed_datapacks' at the same time it will fail.
